spring.application.name=scalingo
server.port=${PORT}
##custom="test"
spring.jpa.hibernate.ddl-auto=update
#
spring.datasource.url=${SCALINGO_MYSQL_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true